### ISSUE TITLE
`ion_schema` should not re-export `ion_rs`

### ISSUE THREAD

**Issue by popematt** [amazon-ion/ion-schema-rust#137]
**The current situation:**

If you're already using `ion_rs`, and then you want to start using `ion_schema`, you may have to change a lot of your imports from `ion_rs::` to `ion_schema::external::ion_rs::`. As long as the versions are the same, this should be a fairly mechanical change that an IDE can handle for you. If the versions are different, then it may be more complex to switch.

In addition, whenever there is a new version of `ion_rs`, and you are using `ion_schema`, you have to wait for `ion_schema` to pick up the latest version of `ion_rs` and release a new version of its own before you can get the benefits of the latest version of `ion_rs`.

**Some alternatives to consider:**

These are just ideas. I'm not sure of the feasibility of all of them.

* Stop exporting `ion_rs` in `ion_schema` and pin to a range of acceptable versions
* ~~Make `ion_rs` export a gated feature in `ion_schema`~~
* Make `ion_schema` a feature in the `ion_rs` crate

This might not be a possibility while both of the libraries are at a `0.x` version, but I think it is something to re-evaluate before releasing a `1.0.0` version of either one of them.

**Comment by dlurton** [comment]
+1 for dropping the re-export of `ion_rs`.  I think that the use of `ion_schema` in applications that don't also directly use `ion_rs` would be rare.  Please don't lock us into a specific version of `ion_rs` and require us to use `ion_schema__external::ion_rs`  just so can also use `ion_schema`.

**Comment by popematt** [comment]
@dlurton do you care to opine on any of the alternatives I've suggested or any ideas you might have?

**Comment by dlurton** [comment]
-1 for: "Make ion_rs export a gated feature in ion_schema" -- this doesn't seem to help the issue at all.

Between the other two, "Stop exporting ion_rs in ion_schema", "Make ion_schema a feature in the ion_rs crate"--either of these I think would be a lot better and it's just a matter of packaging.

It's not good to force the application that wants to use `ion-schema-rust` to use `ion_schema::external::ion_rs`, but it's kind of required right now and leads to one of two somewhat unhappy scenarios when reading Ion from external sources:

- We can parse the payload into an `Element` from `ion_schema::external::ion_rs`, perform validation with `ion_schema`, and then the use the same `Element` instance to map to internal domain objects.  This is sub-optimal because now we're stuck with whatever potentially out of date version of `ion_rs` that `ion_schema` re-exports.  This isn't just limited to mapping to internal domain objects, but lots of other code that manipulates `Element` instances.
- Alternatively, we could parse the payload twice--once to `ion_schema::external::ion_rs` for ISL validation, and again using  regular `ion_rs::value::owned::Element`, but this occurs obvious additional overhead.

**Comment by progwriter** [comment]
Would like to express support for dropping re-exports. Was bitten by this issue, when upgrading from older versions of `ion_rs` and `ion_schema`. The solution (change all imports to `ion_schema::external::ion_rs::` seemed quite counter-intuitive). 

I don't fully understand why the re-export is necessary. Is it just go guarantee version compatibility? Surely this is solvable with pinning/appropriate ranges in Cargo.toml?
